API.Lua: api.cpp
	g++ ../../Shared/Common.h api.cpp -o ../../bin/Linux/plugins/API.Lua.so -ldl -shared -fPIC
	g++ ../../Shared/Common.h api.cpp -o ../../bin/Linux/_32/plugins/API.Lua.so -m32 -ldl -shared -fPIC
